import React from 'react';
import {Routes, Route, Link, useParams, useNavigate, Navigate, useLocation} from 'react-router-dom';
import {Heart, Share2, Search, Menu, X, ArrowRight, Phone, MessageCircle, CalendarDays, MapPin, Clock3, Check, LayoutDashboard, Images, Package, Inbox, Users, Settings, Plus, Pencil, Trash2, LogOut, Upload, ChevronLeft} from 'lucide-react';
import {defaultEvents, defaultThemes} from './data';
import {supabase, supabaseConfigured} from './lib/supabase';

const money = n => `₹${Number(n || 0).toLocaleString('en-IN')}`;
const readLocal = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) || fallback; } catch { return fallback; } };
const writeLocal = (key, value) => localStorage.setItem(key, JSON.stringify(value));

function Header({admin=false}){const [open,setOpen]=React.useState(false);return <header className={admin?'header admin-header':'header'}><div className="container nav"><Link to={admin?'/admin':'/'} className="brand"><span>✿</span><div>Righ Events<small>{admin?'Admin Panel':'Events & Decorations'}</small></div></Link><button className="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'navlinks open':'navlinks'}>{admin?<><Link to="/admin">Dashboard</Link><Link to="/admin/themes">Themes</Link></>:<><Link to="/">Home</Link><Link to="/events">Events</Link><Link to="/themes">Themes</Link><Link to="/gallery">Gallery</Link><a href="/#about">About</a><a href="/#contact">Contact</a></>}</nav>{!admin&&<Link to="/enquiry" className="btn btn-primary top-quote">Get a Quote</Link>}</div></header>}

function Footer(){return <footer><div className="container footer"><div><div className="brand"><span>✿</span><div>Righ Events<small>Events & Decorations</small></div></div><p>WE CREATE YOU CELEBRATE !! .</p></div><div><h4>Explore</h4><Link to="/events">Events</Link><Link to="/themes">Themes</Link><Link to="/gallery">Gallery</Link></div><div><h4>Contact</h4><a href="tel:+919346080840">+91 93460 80480</a><a href="https://wa.me/919346080480">WhatsApp</a><a href="mailto:rgeventdecors@gmail.com">rgevents@gmail.com</a></div></div><div className="copyright">© 2026 Righ Events. All rights reserved.</div></footer>}

function useCatalog(){
  const [events,setEvents]=React.useState(()=>readLocal('righ_events',defaultEvents));
  const [themes,setThemes]=React.useState(()=>readLocal('righ_themes',defaultThemes));
  React.useEffect(()=>{if(!supabaseConfigured){writeLocal('righ_events',events);writeLocal('righ_themes',themes)}},[events,themes]);
  React.useEffect(()=>{let cancelled=false;(async()=>{if(!supabaseConfigured)return;const [{data:ev},{data:th}]=await Promise.all([supabase.from('events').select('*').eq('active',true).order('name'),supabase.from('themes').select('*,theme_images(url,sort_order)').eq('active',true).order('created_at',{ascending:false})]);if(cancelled)return;if(ev?.length)setEvents(ev);if(th){setThemes(th.map(t=>({...t,image_url:t.image_url||t.theme_images?.sort((a,b)=>(a.sort_order||0)-(b.sort_order||0))[0]?.url||'',images:(t.theme_images||[]).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)).map(x=>x.url)})))}})();return()=>{cancelled=true}},[]);
  return {events,themes,setEvents,setThemes};
}

function Home(){const {events,themes}=useCatalog();return <><Header/><main><section className="hero"><div className="hero-overlay"/><div className="container hero-content"><p className="eyebrow">RIGH EVENTS • EVENT DECORATION</p><h1>Make Your<br/><em>Moments Beautiful</em></h1><p>Choose your event, explore our decoration themes and find the perfect setup for your celebration.</p><div className="actions"><Link to="/events" className="btn btn-primary">Choose Your Event <ArrowRight size={17}/></Link><Link to="/enquiry" className="btn btn-light">Get a Quote</Link></div></div></section><section className="trust"><div>✦ Creative Designs</div><div>◈ Multiple Themes</div><div>◉ Transparent Pricing</div><div>♧ Professional Team</div></section><section className="section container"><SectionTitle title="Choose Your Event" sub="Select an event to explore its decoration themes"/><div className="event-grid">{events.slice(0,6).map(e=><EventCard key={e.id} e={e}/>)}</div><div className="center"><Link to="/events" className="text-link">View all events <ArrowRight size={16}/></Link></div></section><section className="dark-banner"><div className="container dark-inner"><div><p className="eyebrow">YOUR VISION, OUR CREATION</p><h2>One Event. Multiple Themes.<br/>Choose What You Love.</h2></div><Link to="/events" className="btn btn-light">Explore Events</Link></div></section><section className="section container"><SectionTitle title="Popular Themes" sub="A few of our favourite decoration styles"/><div className="theme-grid">{themes.slice(0,6).map(t=><ThemeCard key={t.id} t={t} events={events}/>)}</div></section></main><Footer/></>}
function SectionTitle({title,sub}){return <div className="section-title"><h2>{title}</h2><p>{sub}</p></div>}
function EventCard({e}){const {themes}=useCatalog();const count=themes.filter(t=>t.event_id===e.id).length;return <Link className="event-card" to={`/events/${e.id}`}><img src={e.image}/><div><h3>{e.icon} {e.name}</h3><p>{count} Themes Available</p></div></Link>}
function ThemeCard({t,events}){const event=events?.find(e=>e.id===t.event_id);return <div className="theme-card"><Link to={`/themes/${t.id}`} className="theme-image"><img src={t.image_url}/><span className="badge">{t.tag||event?.name}</span></Link><div className="theme-info"><p className="mini-event">{event?.icon} {event?.name}</p><h3>{t.name}</h3><div className="price">{money(t.price)} <small>Starting Price</small></div><Link to={`/themes/${t.id}`} className="btn btn-primary btn-small">View Theme</Link></div></div>}

function Events(){const {events}=useCatalog();return <><Header/><div className="page-head"><div className="container"><p className="eyebrow">RIGH EVENTS</p><h1>What Are You Celebrating?</h1><p>Choose the event type to see the themes available for it.</p></div></div><main className="section container"><div className="event-grid large">{events.map(e=><EventCard key={e.id} e={e}/>)}</div></main><Footer/></>}
function Themes(){const {events,themes}=useCatalog();const [q,setQ]=React.useState('');const [event,setEvent]=React.useState('');const filtered=themes.filter(t=>(!event||t.event_id===event)&&(!q||t.name.toLowerCase().includes(q.toLowerCase())));return <><Header/><div className="page-head"><div className="container"><p className="eyebrow">THEME GALLERY</p><h1>All Decoration Themes</h1><p>Browse themes and compare starting prices.</p></div></div><main className="section container"><div className="filterbar"><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search themes..."/></div><select value={event} onChange={e=>setEvent(e.target.value)}><option value="">All Events</option>{events.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></div><div className="theme-grid">{filtered.map(t=><ThemeCard key={t.id} t={t} events={events}/>)}</div>{!filtered.length&&<Empty text="No themes found for this selection."/>}</main><Footer/></>}
function EventThemes(){const {id}=useParams();const {events,themes}=useCatalog();const event=events.find(e=>e.id===id);const list=themes.filter(t=>t.event_id===id);if(!event)return <Navigate to="/events"/>;return <><Header/><div className="event-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(20,14,20,.72),rgba(20,14,20,.25)),url(${event.image})`}}><div className="container"><Link to="/events" className="back-link"><ChevronLeft size={16}/> All Events</Link><div><span className="event-icon">{event.icon}</span><p className="eyebrow">RIGH EVENTS</p><h1>{event.name} Decorations</h1><p>{list.length} themes available. Choose a style that suits your celebration.</p></div></div></div><main className="section container"><div className="theme-grid">{list.map(t=><ThemeCard key={t.id} t={t} events={events}/>)}</div>{!list.length&&<Empty text="No themes have been added for this event yet."/>}</main><Footer/></>}
function ThemeDetails(){const {id}=useParams();const {events,themes}=useCatalog();const t=themes.find(x=>x.id===id);if(!t)return <Navigate to="/themes"/>;const event=events.find(e=>e.id===t.event_id);const gallery=[t.image_url,...(t.images||[])].filter(Boolean);return <><Header/><main className="container detail-page"><div className="breadcrumbs"><Link to="/events">Events</Link> / <Link to={`/events/${event?.id}`}>{event?.name}</Link> / {t.name}</div><div className="detail-grid"><div><img className="detail-main-img" src={gallery[0]}/><div className="thumbs">{gallery.slice(0,6).map((src,i)=><img key={i} src={src}/>)}</div></div><div className="detail-copy"><div className="detail-actions"><span className="badge">{t.tag||'Theme'}</span><span><Heart size={19}/><Share2 size={19}/></span></div><p className="mini-event">{event?.icon} {event?.name}</p><h1>{t.name}</h1><p className="lead">{t.description}</p><div className="big-price">{money(t.price)} <small>Starting Price</small></div><h3>Decoration Includes</h3><div className="include-grid">{(t.includes||[]).map(x=><div key={x}><Check size={17}/>{x}</div>)}</div><div className="detail-meta"><span><Clock3/>3–4 hours</span><span><CalendarDays/>Customizable</span><span><MapPin/>Indoor / Outdoor</span></div><div className="actions full"><Link to={`/enquiry?theme=${t.id}`} className="btn btn-primary">Request a Quote</Link><Link to={`/enquiry?theme=${t.id}`} className="btn btn-outline">Book This Theme</Link></div><a className="whatsapp" href={`https://wa.me/919999999999?text=${encodeURIComponent(`Hi Righ Events, I am interested in ${t.name} for ${event?.name}.`)}`}><MessageCircle size={18}/> Chat on WhatsApp</a></div></div></main><Footer/></>}
function Enquiry(){const {events,themes}=useCatalog();const params=new URLSearchParams(useLocation().search);const initial=params.get('theme')||'';const [done,setDone]=React.useState(false);const [form,setForm]=React.useState({name:'',phone:'',email:'',event:'',theme:initial,date:'',guests:'',location:'',message:''});const update=e=>setForm({...form,[e.target.name]:e.target.value});if(done)return <main className="form-page"><div className="form-card success"><div className="success-icon">✓</div><h1>Enquiry Received</h1><p>Thank you. The Righ Events team will contact you shortly.</p><Link to="/events" className="btn btn-primary">Explore More Themes</Link></div></main>;return <><Header/><main className="form-page"><div className="form-card"><p className="eyebrow">LET'S PLAN IT</p><h1>Request a Quote</h1><p>Tell us about your event and preferred decoration.</p><form onSubmit={e=>{e.preventDefault();const arr=readLocal('righ_enquiries',[]);writeLocal('righ_enquiries',[{...form,id:Date.now(),status:'New'},...arr]);setDone(true)}}><label>Your Name *<input name="name" value={form.name} onChange={update} required placeholder="Enter your name"/></label><label>Phone Number *<input name="phone" value={form.phone} onChange={update} required placeholder="Enter your phone number"/></label><label>Email<input name="email" value={form.email} onChange={update} type="email" placeholder="Enter your email"/></label><div className="two"><label>Event Type *<select name="event" value={form.event} onChange={update} required><option value="">Select event</option>{events.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label><label>Selected Theme<select name="theme" value={form.theme} onChange={update}><option value="">Select a theme</option>{themes.filter(t=>!form.event||t.event_id===form.event).map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label></div><div className="two"><label>Event Date *<input name="date" value={form.date} onChange={update} type="date" required/></label><label>Expected Guests<input name="guests" value={form.guests} onChange={update} type="number" placeholder="Number of guests"/></label></div><label>Event Location *<input name="location" value={form.location} onChange={update} required placeholder="Enter event location"/></label><label>Additional Requirements<textarea name="message" value={form.message} onChange={update} rows="4" placeholder="Tell us about your requirements..."/></label><button className="btn btn-primary submit" type="submit">Send Enquiry <ArrowRight size={17}/></button></form></div></main></>}
function Gallery(){const {themes}=useCatalog();const imgs=themes.flatMap(t=>[t.image_url,...(t.images||[])]).filter(Boolean);return <><Header/><div className="page-head"><div className="container"><p className="eyebrow">OUR WORK</p><h1>Decoration Gallery</h1><p>Real theme photos and decoration ideas.</p></div></div><main className="section container"><div className="gallery">{imgs.map((src,i)=><img key={i} src={src}/>)}</div></main><Footer/></>}

function AdminLayout({children}){const nav=useNavigate();async function logout(){sessionStorage.removeItem('righ_demo_admin');if(supabaseConfigured)await supabase.auth.signOut();nav('/admin/login')}return <><Header admin/><div className="admin-layout"><aside className="sidebar"><Link to="/admin"><LayoutDashboard/>Dashboard</Link><Link to="/admin/themes"><Images/>Themes</Link><Link to="/events"><CalendarDays/>View Website</Link><Link to="/admin/enquiries"><Inbox/>Enquiries</Link><Link><Package/>Packages</Link><Link><Users/>Customers</Link><Link><Settings/>Settings</Link><button onClick={logout} className="sidebar-logout"><LogOut/>Logout</button></aside><main className="admin-main">{children}</main></div></>}
function ProtectedAdmin({children}){const [loading,setLoading]=React.useState(supabaseConfigured);const [ok,setOk]=React.useState(!supabaseConfigured || sessionStorage.getItem('righ_demo_admin')==='1');React.useEffect(()=>{if(!supabaseConfigured)return;let alive=true;supabase.auth.getUser().then(async({data})=>{if(!alive)return;if(!data.user){setOk(false);setLoading(false);return}const {data:p}=await supabase.from('profiles').select('role').eq('id',data.user.id).single();setOk(p?.role==='admin');setLoading(false)});return()=>{alive=false}},[]);if(loading)return <div className="loading">Checking admin access…</div>;if(!ok)return <Navigate to="/admin/login" replace/>;return children;}
function AdminLogin(){const nav=useNavigate();const [email,setEmail]=React.useState('');const [password,setPassword]=React.useState('');const [error,setError]=React.useState('');async function submit(e){e.preventDefault();setError('');if(!supabaseConfigured){sessionStorage.setItem('righ_demo_admin','1');nav('/admin');return}const {error}=await supabase.auth.signInWithPassword({email,password});if(error){setError(error.message);return}nav('/admin')}return <main className="form-page"><div className="form-card login-card"><div className="brand center-brand"><span>✿</span><div>Righ Events<small>Admin Panel</small></div></div><p className="eyebrow">SECURE LOGIN</p><h1>Admin Login</h1><p>Manage events, themes, photos and prices.</p><form onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label>{error&&<div className="error-box">{error}</div>}<button className="btn btn-primary submit">Login <ArrowRight size={17}/></button>{!supabaseConfigured&&<p className="demo-note">Supabase is not configured yet, so this opens a local demo admin. Add the Supabase environment variables before deploying.</p>}</form><Link to="/" className="back-link dark">← Back to website</Link></div></main>}
function AdminTitle({title,button}){return <div className="admin-title"><div><h1>{title}</h1><p>Righ Events management panel.</p></div>{button}</div>}
function AdminDashboard(){const {events,themes}=useCatalog();const enquiries=readLocal('righ_enquiries',[]);return <AdminLayout><AdminTitle title="Dashboard" button={<Link to="/admin/themes" className="btn btn-primary"><Plus size={17}/> Add Theme</Link>}/><div className="stats"><Stat icon="◉" title="Total Themes" value={themes.length}/><Stat icon="✉" title="Enquiries" value={enquiries.length}/><Stat icon="▣" title="Event Types" value={events.length}/><Stat icon="✦" title="Published Themes" value={themes.length}/></div><div className="admin-panels"><div className="panel"><h3>Event Types</h3><div className="event-admin-list">{events.map(e=><div key={e.id}><span>{e.icon}</span><strong>{e.name}</strong><small>{themes.filter(t=>t.event_id===e.id).length} themes</small></div>)}</div></div><div className="panel"><h3>Recent Enquiries</h3>{enquiries.slice(0,5).map(x=><div className="enquiry-row" key={x.id}><strong>{x.name}</strong><span>{x.event||'—'}</span><b>{x.status}</b></div>)}{!enquiries.length&&<Empty text="No enquiries yet."/>}</div></div></AdminLayout>}
function Stat({icon,title,value}){return <div className="stat"><div className="stat-icon">{icon}</div><div><strong>{value}</strong><span>{title}</span></div></div>}

function AdminThemes(){const {events,themes,setThemes}=useCatalog();const [editing,setEditing]=React.useState(null);const [eventFilter,setEventFilter]=React.useState('');const [q,setQ]=React.useState('');const list=themes.filter(t=>(!eventFilter||t.event_id===eventFilter)&&(!q||t.name.toLowerCase().includes(q.toLowerCase())));
async function saveTheme(theme){try{let item={...theme,price:Number(theme.price),image_url:theme.image_url||''};if(supabaseConfigured){item.id=item.id||crypto.randomUUID();const {error}=await supabase.from('themes').upsert({id:item.id,event_id:item.event_id,name:item.name,description:item.description||'',price:item.price,tag:item.tag||'',includes:item.includes||[],image_url:item.image_url||'',active:true},{onConflict:'id'});if(error)throw error;for(let i=0;i<(theme.pendingFiles||[]).length;i++){const file=theme.pendingFiles[i].file;const path=`${item.id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await supabase.storage.from('theme-images').upload(path,file);if(up.error)throw up.error;const {data:urlData}=supabase.storage.from('theme-images').getPublicUrl(path);await supabase.from('theme_images').insert({theme_id:item.id,url:urlData.publicUrl,sort_order:i});if(!item.image_url){item.image_url=urlData.publicUrl;await supabase.from('themes').update({image_url:item.image_url}).eq('id',item.id)}}const {data:rows}=await supabase.from('themes').select('*,theme_images(url,sort_order)').eq('active',true).order('created_at',{ascending:false});setThemes((rows||[]).map(t=>({...t,images:(t.theme_images||[]).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)).map(x=>x.url)})))}else{const previews=(theme.pendingFiles||[]).map(x=>x.preview);item.images=[...(item.images||[]),...previews];if(!item.image_url)item.image_url=previews[0]||'';setThemes(prev=>theme.id?prev.map(t=>t.id===theme.id?item:t):[item,...prev])}setEditing(null)}catch(err){alert(err.message||'Could not save theme')}}
async function remove(id){if(!confirm('Delete this theme?'))return;if(supabaseConfigured){const {error}=await supabase.from('themes').update({active:false}).eq('id',id);if(error){alert(error.message);return}}setThemes(prev=>prev.filter(t=>t.id!==id))}
return <AdminLayout><AdminTitle title="Themes" button={<button onClick={()=>setEditing({name:'',event_id:events[0]?.id||'',price:'',tag:'',description:'',image_url:'',images:[],includes:[],pendingFiles:[]})} className="btn btn-primary"><Plus size={17}/> Add New Theme</button>}/><div className="panel table-panel"><div className="toolbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search themes..."/></div><select value={eventFilter} onChange={e=>setEventFilter(e.target.value)}><option value="">All Events</option>{events.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></div><table><thead><tr><th>Theme</th><th>Event</th><th>Price</th><th>Photos</th><th>Actions</th></tr></thead><tbody>{list.map(t=><tr key={t.id}><td><div className="table-theme"><img src={t.image_url}/><strong>{t.name}</strong></div></td><td>{events.find(e=>e.id===t.event_id)?.name}</td><td>{money(t.price)}</td><td>{1+(t.images?.length||0)}</td><td><button className="icon-btn" onClick={()=>setEditing({...t,pendingFiles:[]})}><Pencil size={16}/></button><button className="icon-btn" onClick={()=>remove(t.id)}><Trash2 size={16}/></button></td></tr>)}</tbody></table>{!list.length&&<Empty text="No themes in this event yet."/>}</div>{editing&&<ThemeEditor events={events} initial={editing} onSave={saveTheme} onClose={()=>setEditing(null)}/>}</AdminLayout>}

function ThemeEditor({events,initial,onSave,onClose}){const [form,setForm]=React.useState({...initial,includes:initial.includes||[],images:initial.images||[],pendingFiles:initial.pendingFiles||[]});const [previews,setPreviews]=React.useState([]);const update=(k,v)=>setForm(f=>({...f,[k]:v}));const addFiles=e=>{[...e.target.files].forEach(file=>{const r=new FileReader();r.onload=()=>{setForm(f=>({...f,pendingFiles:[...(f.pendingFiles||[]),{name:file.name,file,preview:r.result}]}));setPreviews(p=>[...p,r.result])};r.readAsDataURL(file)})};const existing=[form.image_url,...(form.images||[])].filter(Boolean);return <div className="modal-backdrop"><div className="theme-editor"><div className="editor-head"><div><p className="eyebrow">ADMIN</p><h2>{form.id?'Edit Theme':'Add New Theme'}</h2></div><button onClick={onClose} type="button" className="icon-btn"><X/></button></div><form onSubmit={e=>{e.preventDefault();onSave(form)}} className="editor-form"><div className="two"><label>Theme Name *<input required value={form.name} onChange={e=>update('name',e.target.value)} placeholder="Royal Wedding Theme"/></label><label>Event Type *<select value={form.event_id} onChange={e=>update('event_id',e.target.value)}>{events.map(e=><option value={e.id} key={e.id}>{e.icon} {e.name}</option>)}</select></label></div><div className="two"><label>Price *<input required type="number" min="0" value={form.price} onChange={e=>update('price',e.target.value)} placeholder="25000"/></label><label>Theme Tag<input value={form.tag||''} onChange={e=>update('tag',e.target.value)} placeholder="Luxury / Kids / Floral"/></label></div><label>Description<textarea rows="3" value={form.description||''} onChange={e=>update('description',e.target.value)} placeholder="Describe this decoration theme..."/></label><label>Included Items<input value={(form.includes||[]).join(', ')} onChange={e=>update('includes',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))} placeholder="Backdrop, Balloons, Cake table, Lights"/></label><div className="upload-box"><div><Upload size={24}/><strong>Theme Photos</strong><p>Upload multiple JPG, PNG or WEBP images.</p></div><label className="btn btn-outline upload-btn">+ Choose Photos<input hidden type="file" accept="image/*" multiple onChange={addFiles}/></label></div><div className="photo-grid">{[...existing,...previews].map((src,i)=><div className="photo-thumb" key={i}><img src={src}/>{i===0&&<span>Main</span>}</div>)}</div><div className="editor-actions"><button type="button" onClick={onClose} className="btn btn-outline">Cancel</button><button className="btn btn-primary">Save Theme</button></div></form></div></div>}

function AdminEnquiries(){const [items,setItems]=React.useState(()=>readLocal('righ_enquiries',[]));function remove(id){setItems(x=>{const n=x.filter(i=>i.id!==id);writeLocal('righ_enquiries',n);return n})}return <AdminLayout><AdminTitle title="Enquiries"/><div className="panel table-panel"><table><thead><tr><th>Name</th><th>Phone</th><th>Event</th><th>Date</th><th>Location</th><th>Status</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.phone}</td><td>{x.event}</td><td>{x.date}</td><td>{x.location}</td><td><span className="status new">{x.status}</span></td><td><button className="icon-btn" onClick={()=>remove(x.id)}><Trash2 size={15}/></button></td></tr>)}</tbody></table>{!items.length&&<Empty text="No enquiries yet. Customer enquiries will appear here."/>}</div></AdminLayout>}
function Empty({text}){return <div className="empty">{text}</div>}

export default function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/events" element={<Events/>}/><Route path="/events/:id" element={<EventThemes/>}/><Route path="/themes" element={<Themes/>}/><Route path="/themes/:id" element={<ThemeDetails/>}/><Route path="/enquiry" element={<Enquiry/>}/><Route path="/gallery" element={<Gallery/>}/><Route path="/admin/login" element={<AdminLogin/>}/><Route path="/admin" element={<ProtectedAdmin><AdminDashboard/></ProtectedAdmin>}/><Route path="/admin/themes" element={<ProtectedAdmin><AdminThemes/></ProtectedAdmin>}/><Route path="/admin/enquiries" element={<ProtectedAdmin><AdminEnquiries/></ProtectedAdmin>}/></Routes>}
